services:
  mysql:
    image: mysql:8.0
    container_name: biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: biblioteca_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - biblioteca_network

volumes:
  mysql_data:

networks:
  biblioteca_network:
    driver: bridge
